### ISSUE TITLE
403 Error from DeepL 

### ISSUE THREAD

**Issue by Beoo-666** [olijeffers0n/XLang#9]
![image](https://user-images.githubusercontent.com/55978588/123559402-6ef95180-d7ce-11eb-9fa8-6c341f090e97.png)

**Comment by Evil-Space-Wizard** [comment]
Can you please post your `config.yml`?

This might be an issue with an invalid API Key,
or the wrong API Target.

**Comment by olijeffers0n** [comment]
Issue closed due to inactivity
